build:
  environment:
    php: '7.2.0'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        relational: false
        concatenation: true
filter:
  excluded_paths:
    - 'tests/*'
    - 'vendor/*'