language: php
sudo: false
dist: trusty
env:
  global:
    - XDEBUG_MODE=coverage
php:
  - 7.4
  - 7.3
  - 7.2

script:
  - composer install
  - php vendor/bin/codecept run --coverage --coverage-xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
